export enum TipoEventoEmergencia {
  GRITO_AUXILIO = 'GRITO_AUXILIO',
  ACCIDENTE = 'ACCIDENTE',
  PELEA = 'PELEA',
  SONIDO_ANOMALO = 'SONIDO_ANOMALO',
  EMERGENCIA_GENERAL = 'EMERGENCIA_GENERAL',
}
